Update docker-compose.yml
fix typo "false"

```
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.functions.environment.VERIFY_JWT contains false, which is an invalid type, it should be a string, number, or a null
```